### ISSUE TITLE
昔作った.onnxがonnxruntime 1.18でloadできない

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/vv_core_inference#27]
## 概要

昔作った.onnxがonnxruntime 1.18でloadできない問題が発生しています。
このままではonnxruntimeの1.18バージョンアップができないので、なんとかしたいところです。

とりあえず知見を集めるべく、issueを作ってみました。

## 検証方法

`onnxruntime-1.18`ブランチを作ってみました。
こちらのブランチに移動して`pip install -r requirements.txt`すれば環境が構築できます。
（python 3.10環境が必要です）

`voicevox_core`内に.onnxがあるので、そちらを持ってきて試すのが手っ取り早いです。
`~/Github/voicevox_core`にVOICEVOX COREリポジトリのcloneがあるとして、こちらのbashスクリプトで検証できます。

```bash
set -eux

working_dir=working/
rm -rf $working_dir
mkdir -p $working_dir

cp ~/Github/voicevox_core/model/sample.vvm/predict_duration.onnx "$working_dir/duration.onnx"
cp ~/Github/voicevox_core/model/sample.vvm/predict_intonation.onnx "$working_dir/intonation.onnx"
cp ~/Github/voicevox_core/model/sample.vvm/decode.onnx "$working_dir/decode.onnx"

python run.py \
  --yukarin_s_model_dir "$working_dir" \
  --yukarin_sa_model_dir "$working_dir" \
  --yukarin_sosoa_model_dir "$working_dir" \
  --hifigan_model_dir "$working_dir" \
  --method onnx \
  --speaker_ids 5 9
```

実行ログ↓
```log
+ working_dir=working/
+ rm -rf working/
+ mkdir -p working/
+ cp /Users/[user name]/Github/voicevox_core/model/sample.vvm/predict_duration.onnx working//duration.onnx
+ cp /Users/[user name]/Github/voicevox_core/model/sample.vvm/predict_intonation.onnx working//intonation.onnx
+ cp /Users/[user name]/Github/voicevox_core/model/sample.vvm/decode.onnx working//decode.onnx
+ python run.py --yukarin_s_model_dir working/ --yukarin_sa_model_dir working/ --yukarin_sosoa_model_dir working/ --hifigan_model_dir working/ --method onnx --speaker_ids 5 9
Traceback (most recent call last):
  File "/Users/[user name]/Github/vv_core_inference/run.py", line 99, in <module>
    run(**vars(parser.parse_args()))
  File "/Users/[user name]/Github/vv_core_inference/run.py", line 59, in run
    decode_forwarder = make_decode_forwarder(
  File "/Users/[user name]/Github/vv_core_inference/vv_core_inference/onnx_decode_forwarder.py", line 12, in make_decode_forwarder
    session = onnxruntime.InferenceSession(
  File "/Users/[user name]/Github/vv_core_inference/.venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/Users/[user name]/Github/vv_core_inference/.venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from working/decode.onnx failed:Node (Unsqueeze_481) Op (Unsqueeze) [ShapeInferenceError] values in 'axes' are beyond the bounds of the computed output shape
```

**Comment by Hiroshiba** [comment]
Discordでのやり取りメモ 📝 
https://discord.com/channels/879570910208733277/893889888208977960/1274198132111966251

* ONNX v1.15.0 → v1.16.0の変更により起きたもの。ONNX RuntimeがONNXに当てるパッチも関係無い (ちなみに調査で[onnx.checker.check_model](https://onnx.ai/onnx/api/checker.html#onnx.checker.check_model)を用いるときは%60full_check=True%60としなければならない)
* おそらく[onnx/onnx#5967](https://github.com/onnx/onnx/pull/5967)により起きている。この一つ前なら%60check_model%60が通る。つまりこの%60+54-20%60の「shape inferenceのfix」により起きている

---

* このコミットはaxes非指定のSqueezeにshape inferenceがついたということなのでそれに関連する部分の影響でしょうか
* https://github.com/Hiroshiba/vv_core_inference/blob/main/vv_core_inference/make_yukarin_sosoa_forwarder.py#L128
* (dynamic axesを含む場合のshape inferenceがバグっているのか詳しいことは分かりませんがここが怪しそう）
* 長さ１のf0を入力したときなどにバグる実装なので元を直した方が良いとは思いますが、対症療法的には対応するSqueezeのaxesを明示するコンバーターを書けば何とかなりそう？

**Comment by Hiroshiba** [comment]
可視化してみた感じ、
`f0　→　Unsqueeze　→　shape　→　ConstantOfShape　→　Squeeze　→　Unsqueeze`
となってるとこの２つ目のUnsqueezeで落ちてそうでした。

そのあと　`Equal　→　Where　→　Softmax`　と続いてます。
おそらくself attentionの部分で、落ちてるUnsqueezeは `mask.unsqueeze(1)` してるとこだと思います。つまり問題ない。

その前のSqueezeはここ↓で、次元を指定せずに`squeeze()`してました。ここの結果axesがわからなくなっちゃってそう？
https://github.com/Hiroshiba/vv_core_inference/blob/5492845bc49f8bf8be9739ef55039ceb59ae0ba9/vv_core_inference/make_yukarin_sosoa_forwarder.py#L128-L129

**Comment by Hiroshiba** [comment]
onnx 1.16でOPSET 21に変換してみましたが、同じ場所で落ちて、エラーが変わるだけでした。
```log
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from working/decode.onnx failed:Node (Unsqueeze_481) Op (Unsqueeze) [ShapeInferenceError] Unexpected axis value: 1. Expected range [-1, 1)
```

<details><summary>コード</summary>

変換コード `convert_to_onnx1.16.py`
```py
"""
ONNX 1.16に変換するためのスクリプト。
"""

import argparse

import onnx
from onnx import version_converter

parser = argparse.ArgumentParser()
parser.add_argument("input", help="Input ONNX model")
parser.add_argument("output", help="Output ONNX model")
args = parser.parse_args()

OPSET = onnx.defs.onnx_opset_version()

old_model = onnx.load(args.input)

updated_model = version_converter.convert_version(old_model, target_version=OPSET)
onnx.save(updated_model, args.output)
```

スクリプト
```bash
set -eux

working_dir=working/
rm -rf $working_dir
mkdir -p $working_dir

cp ~/Github/voicevox_core/model/sample.vvm/predict_duration.onnx "$working_dir/duration.onnx"
cp ~/Github/voicevox_core/model/sample.vvm/predict_intonation.onnx "$working_dir/intonation.onnx"
cp ~/Github/voicevox_core/model/sample.vvm/decode.onnx "$working_dir/decode.onnx"

python convert_to_onnx1.16.py \
  "$working_dir/decode.onnx" \
  "$working_dir/decode.onnx"

python run.py \
  --yukarin_s_model_dir "$working_dir" \
  --yukarin_sa_model_dir "$working_dir" \
  --yukarin_sosoa_model_dir "$working_dir" \
  --hifigan_model_dir "$working_dir" \
  --method onnx \
  --speaker_ids 5 9
```

</details>

**Comment by Hiroshiba** [comment]
pytorch 1.13/onnx 1.16/onnxruntime 1.18で作った.onnxは普通にonnxruntime 1.18で読み込めるので、差を見比べました。
Unsqeezeの部分が違っていそう？
`attributes axes 1`だとダメで、`INPUTS axes`として別のとこを参照してそうでした。
ちゃんとonnx知らないのですが、こっち変えるのは相当大変そう･･･？
<details><summary>比較画像</summary>

以前の
![image](https://github.com/user-attachments/assets/e78ccb90-a5c5-4d0d-813e-a32b8073026a)

新しく作ったの
![image](https://github.com/user-attachments/assets/52a5ea43-a7d5-4cb2-b7ba-a73636254944)

</details>

**Comment by Yosshi999** [comment]
v13以降のUnsqueezeはaxesを実行時に指定できる(inputに指定できる)ようですね。そのスクショを見た感じv13でもaxesの右に＋マークがついているので、結局定数(initializerからinputへの入力)としてほぞんされているかもしれないです。その＋をクリックすると展開できます

**Comment by Hiroshiba** [comment]
@Yosshi999 ありがとうございます！！
見てみたら、確かに何かが保存されていそうでした！`[1]`のTensorっぽみですね･･･。
<details><summary>画像</summary>

![image](https://github.com/user-attachments/assets/bef2e06d-ae21-4d09-a60e-6f154ee6b5c5)

</details>

**Comment by Hiroshiba** [comment]
v13に変換すると、Unsqueezeは問題ない？っぽいもの（axesに値が入ってるもの）になる一方、Squeezeがスカラ値っぽくなってました。
<details>

↓v13に変換したonnxのUnsqueeze
![image](https://github.com/user-attachments/assets/df87b559-2037-42e5-8c6c-4f176fea9d2e)

↓v13に変換したonnxのSqueeze
![image](https://github.com/user-attachments/assets/c03579d1-f2a7-4087-8119-441dbc6ae998)

</details>

ちなみにこれは`(Unsqueeze) [ShapeInferenceError] Unexpected axis value: 1. Expected range [-1, 1)`というエラーが出ます。

正しく読める.onnxの方のSqueezeはこうなってました。
<details>

![image](https://github.com/user-attachments/assets/0dede2d8-3a99-4ff1-81c3-ac829118f4ae)

</details>

Squeezeのaxes引数？を0にすれば解決する･･･？
（バッチサイズ１にunsqueezeしてて、そこのsqueezeをするのがここの目的なはず）

**Comment by Hiroshiba** [comment]
@Yosshi999 またまたになってしまうのですが、onnxモデルの変換で力をお借りできないでしょうか･･･ 🙇 

[VOICEVOX COREリポジトリにあるonnxファイル](https://github.com/VOICEVOX/voicevox_core/tree/a15753f4b4c9196c870b09de39ee75e37a19a4ed/model/sample.vvm)を変換し、`onnxruntime-1.18`ブランチの環境で`run.py`が実行できれば勝ちなはずです！
再現方法はこのissueのdescriptionに詳しく書いています。
（といってもかなり整備できているので、リネームして`run.py`実行するだけなのですが）

decodeにはUnsqueezeが３つありますが、３つとも変換が必要なのか等は現状不明です。
Discordでやりとりがあったように、Squeeze側に引数`[0, 2]`を追加できればあるいは･･･という感じ･･･でしょうか。

新しいonnxruntimeで使えればその分WebGPUでの速度なども追従されるため、いろいろできる範囲も増えていくと踏んでいます！
もしよければ･･･！！！

**Comment by Yosshi999** [comment]
https://github.com/onnx/onnx/issues/6313
これが完了したので多分次のバージョンで直ってるんじゃないかと思います

**Comment by Hiroshiba** [comment]
おおおおありがとうございます！！！！！！！

とりあえずこのissueはopenし続けますが、onnxファイルをどうにかしなくても良いかもという方針で動こうと思います！！

**Comment by sevenc-nanashi** [comment]
Onnxruntme 1.20.1でもまだ直ってなさそう？：
```
In [12]: s = onnxruntime.InferenceSession("./model/sample.vvm/predict_spectrogram.onnx")
---------------------------------------------------------------------------
Fail                                      Traceback (most recent call last)
Cell In[12], line 1
----> 1 s = onnxruntime.InferenceSession("./model/sample.vvm/predict_spectrogram.onnx")

File ~/.rye/tools/ipython/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:465, in InferenceSession.__init__(self, path_or_bytes, sess_options, providers, provider_options, **kwargs)
    462 disabled_optimizers = kwargs.get("disabled_optimizers")
    464 try:
--> 465     self._create_inference_session(providers, provider_options, disabled_optimizers)
    466 except (ValueError, RuntimeError) as e:
    467     if self._enable_fallback:

File ~/.rye/tools/ipython/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:526, in InferenceSession._create_inference_session(self, providers, provider_options, disabled_optimizers)
    523 self._register_ep_custom_ops(session_options, providers, provider_options, available_providers)
    525 if self._model_path:
--> 526     sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    527 else:
    528     sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)

Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ./model/sample.vvm/predict_spectrogram.onnx failed:Node (m0.Unsqueeze_482) Op (Unsqueeze) [ShapeInferenceError] values in 'axes' are beyond the bounds of the computed output shape

In [13]: onnxruntime.__version__
Out[13]: '1.20.1'
```

**Comment by qryxip** [comment]
onnx/onnx#6314 ですが、onnx/onnxのリリースにはまだ入ってなさそうです（onnx v1.17.0では見送られたっぽい）。なので

1. onnx/onnx#6314 がリリースされるのを待つ
2. ONNX Runtimeがonnx/onnxのバージョンを上げるのを待つ
3. 2.が含まれたONNX Runtimeがリリースされるのを待つ

ということになりそうです。

ONNX Runtime自体が[onnxに対してパッチ](https://github.com/microsoft/onnxruntime/blob/v1.20.1/cmake/patches/onnx/onnx.patch)してるので、このパッチに onnx/onnx#6314 の内容をねじ込めばなんとかなるかもしれませんが… 
(もしやるとしたら、onnxruntime-builderにpatch for patchを置くことに…？)

**Comment by sevenc-nanashi** [comment]
> このパッチに https://github.com/onnx/onnx/pull/6314 の内容をねじ込めばなんとかなるかもしれませんが…

ローカルでビルドしたところ、動きました！具体的にはこんなパッチを追加しました：
[diff.zip](https://github.com/user-attachments/files/18222321/diff.zip)

ので、 https://github.com/onnx/onnx/pull/6314 が含まれたonnxruntimeのリリースと同時にこのIssueは閉じても良さそう。
